version: '3.8'

services:
  # 1. MySQL for Users, Orders, and Finance
  mysql-db:
    image: mysql:8.0
    container_name: dinesync-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dinesync_db
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # 2. MongoDB for Restaurants and Menus (Supports Geospatial 2dsphere queries)
  mongo-db:
    image: mongo:latest
    container_name: dinesync-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

  # 3. Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 4. Kafka for Event-Driven Messaging
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql-data:
  mongo-data:
